//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T001账号表
    {
        public T001账号表()
        {
            this.T006店铺信息表 = new HashSet<T006店铺信息表>();
            this.T005票务表 = new HashSet<T005票务表>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string UserState { get; set; }
        public string PhotoUrl { get; set; }
    
        public virtual T002验证表 T002验证表 { get; set; }
        public virtual T003用户角色表 T003用户角色表 { get; set; }
        public virtual ICollection<T006店铺信息表> T006店铺信息表 { get; set; }
        public virtual ICollection<T005票务表> T005票务表 { get; set; }
    }
}
