//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T004社团信息表
    {
        public T004社团信息表()
        {
            this.T008海报信息表 = new HashSet<T008海报信息表>();
        }
    
        public string PartyName { get; set; }
        public string Purpose { get; set; }
        public string Property { get; set; }
        public string Task { get; set; }
        public string Activities { get; set; }
        public string FoundingTime { get; set; }
        public string Members { get; set; }
        public string Describe { get; set; }
        public string PartyLogoUrl { get; set; }
    
        public virtual T009社团账号表 T009社团账号表 { get; set; }
        public virtual ICollection<T008海报信息表> T008海报信息表 { get; set; }
    }
}
