//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T005票务表
    {
        public int Id { get; set; }
        public string PostName { get; set; }
        public string UserEmail { get; set; }
    
        public virtual T001账号表 T001账号表 { get; set; }
        public virtual T008海报信息表 T008海报信息表 { get; set; }
    }
}
