//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T006店铺信息表
    {
        public T006店铺信息表()
        {
            this.T007店铺货物表1 = new HashSet<T007店铺货物表>();
        }
    
        public string Name { get; set; }
        public string Introduction { get; set; }
        public string Owners { get; set; }
        public string Contaction { get; set; }
        public string QQ { get; set; }
        public string WeChat { get; set; }
        public int MallID { get; set; }
    
        public virtual T001账号表 T001账号表 { get; set; }
        public virtual ICollection<T007店铺货物表> T007店铺货物表1 { get; set; }
    }
}
