//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T007店铺货物表
    {
        public string GoodName { get; set; }
        public string GoodPhoto { get; set; }
        public string GoodIntroduction { get; set; }
        public Nullable<int> GoodNumber { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public int GoodID { get; set; }
        public int ShopID { get; set; }
    
        public virtual T006店铺信息表 T006店铺信息表1 { get; set; }
    }
}
