//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T009社团账号表
    {
        public string PartyName { get; set; }
        public string Password { get; set; }
        public string State { get; set; }
    
        public virtual T004社团信息表 T004社团信息表 { get; set; }
    }
}
