//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TomatoEntities : DbContext
    {
        public TomatoEntities()
            : base("name=TomatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T001账号表> T001账号表 { get; set; }
        public DbSet<T002验证表> T002验证表 { get; set; }
        public DbSet<T003用户角色表> T003用户角色表 { get; set; }
        public DbSet<T006店铺信息表> T006店铺信息表 { get; set; }
        public DbSet<T007店铺货物表> T007店铺货物表 { get; set; }
        public DbSet<T004社团信息表> T004社团信息表 { get; set; }
        public DbSet<T005票务表> T005票务表 { get; set; }
        public DbSet<T008海报信息表> T008海报信息表 { get; set; }
        public DbSet<T009社团账号表> T009社团账号表 { get; set; }
    }
}
